services:
  backend-flask:
    build:
      context: .  # Set context to project root (PySync-Hub)
      dockerfile: app/Dockerfile  # Specify the correct Dockerfile location
    ports:
      - "5000:5000"
      #- "192.168.1.100:5000:5000" Something like this for specific backend custom ip
    volumes:
      - .:/PySync-Hub  # Mount the entire project for live code updates
      - ./downloads:/PySync-Hub/downloads  # Mount the downloads directory
    env_file:
      - .env
    restart: always

  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    restart: always
    depends_on:
      - backend-flask
    # environment:
    #    - REACT_APP_BACKEND_URL=http://your-custom-ip:5000  # Set the backend URL if needed